[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  publish = "staticfiles"


[context.production.environment]
  DJANGO_SETTINGS_MODULE = "capstone.settings"
  PYTHON_VERSION = "3.9"
