[build]
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput && gunicorn capstone.wsgi:application --bind 0.0.0.0:$PORT"
  publish = "staticfiles"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "capstone.settings"
  PYTHON_VERSION = "3.9"
